name: "Build and Push Docker Image that Supports only a Single Platform"
description: "Build and push a Docker image to GitHub Container Registry"

inputs:
  service-dir:
    description: "Service directory name containing Dockerfile"
    required: true
  image-name:
    description: "Image name to push (e.g., amp-console)"
    required: true
  registry:
    description: "Container registry URL"
    required: true
    default: "ghcr.io"
  registry-org:
    description: "Registry organization/namespace"
    required: true
  tag:
    description: "Image tag (usually release tag)"
    required: true
  platform:
    description: "Target platforms for the Docker image (e.g., linux/amd64)"
    required: true
  build-args:
    description: "Build arguments (multiline string, one per line)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build Docker image
      run: |
        # Parse build-args into docker build format
        BUILD_ARGS=""
        if [ -n "$BUILD_ARGS_INPUT" ]; then
          while IFS= read -r arg; do
            if [ -n "$arg" ]; then
              BUILD_ARGS="$BUILD_ARGS --build-arg $arg"
            fi
          done <<< "$BUILD_ARGS_INPUT"
        fi

        # Build the image using plain docker build
        # Context: ./${{ inputs.service-dir }}
        # Dockerfile: ./${{ inputs.service-dir }}/Dockerfile
        docker build \
          -f ./${{ inputs.service-dir }}/Dockerfile \
          -t ${{ inputs.registry }}/${{ inputs.registry-org }}/${{ inputs.image-name }}:${{ inputs.tag }} \
          $BUILD_ARGS \
          ./${{ inputs.service-dir }}
      shell: bash
      env:
        BUILD_ARGS_INPUT: ${{ inputs.build-args }}

    - name: Push Docker image
      run: |
        docker push ${{ inputs.registry }}/${{ inputs.registry-org }}/${{ inputs.image-name }}:${{ inputs.tag }}
      shell: bash

    - name: Log image details
      run: |
        echo "Built and pushed: ${{ inputs.registry }}/${{ inputs.registry-org }}/${{ inputs.image-name }}:${{ inputs.tag }}"
      shell: bash
